name: Prisma Migrate Deploy PROD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      NEON_POSTGRES_DATABASE_URL: ${{ secrets.NEON_POSTGRES_DATABASE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: pnpm install
      - name: Apply all pending migrations to the database
        run: pnpm dlx prisma migrate deploy
      - name: Generate Fresh Prisma Client
        run: pnpm dlx prisma generate
